config/routes.rb
Rails.application.routes.draw do
  resources :stuffs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stuff.rb
class Stuff
  include Mongoid::Document
  field :name, type: String
  field :price, type: Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stuffs_controller.rb
class StuffsController < ApplicationController
  before_action :set_stuff, only: [:show, :edit, :update, :destroy]

  # GET /stuffs
  # GET /stuffs.json
  def index
    @stuffs = Stuff.all
  end

  # GET /stuffs/1
  # GET /stuffs/1.json
  def show
  end

  # GET /stuffs/new
  def new
    @stuff = Stuff.new
  end

  # GET /stuffs/1/edit
  def edit
  end

  # POST /stuffs
  # POST /stuffs.json
  def create
    @stuff = Stuff.new(stuff_params)

    respond_to do |format|
      if @stuff.save
        format.html { redirect_to @stuff, notice: 'Stuff was successfully created.' }
        format.json { render :show, status: :created, location: @stuff }
      else
        format.html { render :new }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stuffs/1
  # PATCH/PUT /stuffs/1.json
  def update
    respond_to do |format|
      if @stuff.update(stuff_params)
        format.html { redirect_to @stuff, notice: 'Stuff was successfully updated.' }
        format.json { render :show, status: :ok, location: @stuff }
      else
        format.html { render :edit }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuffs/1
  # DELETE /stuffs/1.json
  def destroy
    @stuff.destroy
    respond_to do |format|
      format.html { redirect_to stuffs_url, notice: 'Stuff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stuff
      @stuff = Stuff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stuff_params
      params.require(:stuff).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stuffs_helper.rb
module StuffsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stuffs/_form.html.erb
<%= form_for(stuff) do |f| %>
  <% if stuff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stuff.errors.count, "error") %> prohibited this stuff from being saved:</h2>

      <ul>
      <% stuff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stuffs/edit.html.erb
<h1>Editing Stuff</h1>

<%= render 'form', stuff: @stuff %>

<%= link_to 'Show', @stuff %> |
<%= link_to 'Back', stuffs_path %>

app/views/stuffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stuffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stuffs.each do |stuff| %>
      <tr>
        <td><%= stuff.name %></td>
        <td><%= stuff.price %></td>
        <td><%= link_to 'Show', stuff %></td>
        <td><%= link_to 'Edit', edit_stuff_path(stuff) %></td>
        <td><%= link_to 'Destroy', stuff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stuff', new_stuff_path %>

app/views/stuffs/new.html.erb
<h1>New Stuff</h1>

<%= render 'form', stuff: @stuff %>

<%= link_to 'Back', stuffs_path %>

app/views/stuffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stuff.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @stuff.price %>
</p>

<%= link_to 'Edit', edit_stuff_path(@stuff) %> |
<%= link_to 'Back', stuffs_path %>